# Generated by Django 5.1.1 on 2024-09-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidapp', '0002_medicalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='driver_cnic',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='driver_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
