# Generated by Django 5.1.1 on 2024-09-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidapp', '0004_alter_emergencyrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Accepted', 'Accepted'), ('dispatched', 'Dispatched'), ('on_route', 'On Route'), ('Pickedup', 'Pickedup'), ('completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
