# Generated by Django 5.1.1 on 2024-09-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidapp', '0008_alter_emergencyrequest_status_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='is_driver',
            field=models.BooleanField(default=True, verbose_name='Driver Status'),
        ),
    ]
