# Generated by Django 5.1.1 on 2024-09-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidapp', '0009_alter_driver_is_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
