# Generated by Django 5.1.1 on 2024-09-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidapp', '0010_medicalprofile_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('En route', 'En route'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
