# Generated by Django 5.1.1 on 2024-09-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidapp', '0012_alter_emergencyrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Accepted', 'Accepted'), ('enroute', 'Enroute'), ('completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
