# Generated by Django 5.1.1 on 2024-09-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidapp', '0013_alter_emergencyrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
