# Generated by Django 5.1.1 on 2024-09-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidapp', '0014_emergencyrequest_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
