# Generated by Django 5.1.1 on 2024-09-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapidapp', '0015_emergencyrequest_status_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='status_updated_at',
        ),
    ]
