# Generated by Django 5.1.1 on 2024-09-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidapp', '0017_remove_emergencyrequest_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
